@extends('layouts.app')
@section('title', 'Admin Dashboard | KYP')
@section('body')
<div class="panel-shell"><div class="container"><div class="panel">
<div style="display:flex;justify-content:space-between;align-items:center;gap:18px;flex-wrap:wrap"><div><span class="eyebrow" style="color:#057d78;background:#e8fffd">ADMIN CONTROL</span><h1>KYP Administration</h1><p style="color:var(--muted)">Learning, assessment और certification का live central overview।</p></div><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn btn-primary" href="{{ route('admin.users') }}">Users & Enrolments</a><a class="btn btn-primary" href="{{ route('admin.progress') }}">Student Progress</a><a class="btn btn-primary" href="{{ route('admin.assessments') }}">Exams & Questions</a><a class="btn btn-primary" href="{{ route('attendance.index') }}">Attendance</a><a class="btn btn-primary" href="{{ route('admin.results') }}">Results & Certificates</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-light">Logout</button></form></div></div>
<div class="panel-grid">
<div class="panel-card"><h3>Students</h3><div class="metric">{{ $stats['students'] }}</div></div><div class="panel-card"><h3>Teachers</h3><div class="metric">{{ $stats['teachers'] }}</div></div><div class="panel-card"><h3>Active Courses</h3><div class="metric">{{ $stats['courses'] }}</div></div><div class="panel-card"><h3>Learning Sessions</h3><div class="metric">{{ $stats['sessions'] }}</div></div><div class="panel-card"><h3>Active Enrolments</h3><div class="metric">{{ $stats['enrollments'] }}</div></div><div class="panel-card"><h3>Attendance Today</h3><div class="metric">{{ $stats['attendance_today'] }}</div></div><div class="panel-card"><h3>Online Exams</h3><div class="metric">{{ $stats['exams'] }}</div></div><div class="panel-card"><h3>Question Bank</h3><div class="metric">{{ $stats['questions'] }}</div></div><div class="panel-card"><h3>Results</h3><div class="metric">{{ $stats['results'] }}</div></div><div class="panel-card"><h3>Certificates</h3><div class="metric">{{ $stats['certificates'] }}</div></div>
</div></div></div></div>
@endsection
