@extends('layouts.app')
@section('title','Edit Question | KYP')
@section('body')
<div class="panel-shell"><div class="container"><div class="panel"><h1>Edit Bilingual Question</h1>
@if($errors->any())<div style="padding:14px;background:#fff1f2;color:#be123c">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('admin.questions.update',$question) }}">@csrf @method('PUT')
<div class="panel-grid"><label>Course<select name="course_id" required style="width:100%;padding:11px">@foreach($courses as $course)<option value="{{ $course->id }}" @selected($course->id===$question->course_id)>{{ $course->code }}</option>@endforeach</select></label><label>Session<select name="learning_session_id" required style="width:100%;padding:11px">@foreach($courses as $course)@foreach($course->sessions as $session)<option value="{{ $session->id }}" @selected($session->id===$question->learning_session_id)>{{ $course->code }}-{{ $session->session_number }}</option>@endforeach@endforeach</select></label><label>Exam<select name="exam_id" style="width:100%;padding:11px"><option value="">Question bank only</option>@foreach($exams as $exam)<option value="{{ $exam->id }}" @selected($question->exams->contains($exam->id))>{{ $exam->course->code }} — {{ $exam->title_en }}</option>@endforeach</select></label></div>
<div class="panel-grid" style="margin-top:12px"><label>Hindi<textarea name="text_hi" required style="width:100%;padding:11px">{{ $question->text_hi }}</textarea></label><label>English<textarea name="text_en" required style="width:100%;padding:11px">{{ $question->text_en }}</textarea></label></div>
@foreach(['A','B','C','D'] as $key) @php($option=$question->options->firstWhere('option_key',$key)) <div class="panel-grid" style="margin-top:10px"><label>{{ $key }} Hindi<input name="options_hi[{{ $key }}]" value="{{ $option?->text_hi }}" required style="width:100%;padding:10px"></label><label>{{ $key }} English<input name="options_en[{{ $key }}]" value="{{ $option?->text_en }}" required style="width:100%;padding:10px"></label></div>@endforeach
<div class="panel-grid" style="margin-top:12px"><label>Correct<select name="correct_option" style="width:100%;padding:11px">@foreach(['A','B','C','D'] as $key)<option @selected($question->options->firstWhere('option_key',$key)?->is_correct)>{{ $key }}</option>@endforeach</select></label><label>Marks<input type="number" step=".25" name="marks" value="{{ $question->marks }}" required style="width:100%;padding:11px"></label><label>Negative<input type="number" step=".25" name="negative_marks" value="{{ $question->negative_marks }}" required style="width:100%;padding:11px"></label><label>Difficulty<select name="difficulty" style="width:100%;padding:11px">@foreach(['foundation','intermediate','advanced'] as $level)<option @selected($question->difficulty===$level)>{{ $level }}</option>@endforeach</select></label><label>Status<select name="status" style="width:100%;padding:11px"><option value="published" @selected($question->status==='published')>Published</option><option value="draft" @selected($question->status==='draft')>Draft</option></select></label></div>
<input type="hidden" name="explanation_hi" value="{{ $question->explanation_hi }}"><input type="hidden" name="explanation_en" value="{{ $question->explanation_en }}">
<div style="display:flex;gap:10px;margin-top:16px"><button class="btn btn-primary">Save Changes</button><a class="btn btn-light" href="{{ route('admin.assessments') }}">Cancel</a></div></form>
</div></div></div>
@endsection
