<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>KYP Attendance Report</title>

<style>
@page{size:A4 landscape;margin:10mm}
*{box-sizing:border-box}
body{font-family:Arial,sans-serif;margin:0;color:#172b4d;font-size:10px}
.header{display:flex;justify-content:space-between;border-bottom:3px solid #0755a5;padding-bottom:10px}
.header h1{margin:0;color:#062b63;font-size:21px}
.header h2{margin:4px 0;font-size:14px}
.meta{text-align:right;color:#53657d}
.summary{display:grid;grid-template-columns:repeat(7,1fr);gap:5px;margin:12px 0}
.box{border:1px solid #ccd9e8;padding:7px;border-radius:5px}
.box small{display:block;color:#718096;font-size:7px}
.box strong{font-size:13px;color:#062b63}
table{width:100%;border-collapse:collapse;margin-top:10px}
th,td{border:1px solid #ccd9e8;padding:5px;text-align:left;vertical-align:top}
th{background:#eef4fb;font-size:7px;text-transform:uppercase}
.footer{margin-top:18px;display:flex;justify-content:space-between;color:#718096}
.no-print{padding:8px 14px;border:0;border-radius:6px;background:#0755a5;color:#fff;font-weight:bold;cursor:pointer}
@media print{.no-print{display:none}}
</style>
</head>

<body>

<button class="no-print" onclick="window.print()">Print / Save as PDF</button>

<div class="header">
<div>
<h1>KUSHAL YOUTH PROGRAM</h1>
<h2>Attendance Management Report</h2>
<div>MCI Educational Group</div>
</div>

<div class="meta">
Generated: {{ now()->format('d-m-Y h:i A') }}<br>
Filtered Attendance Statement
</div>
</div>

<div class="summary">
<div class="box"><small>RECORDS</small><strong>{{ number_format($summary['records']) }}</strong></div>
<div class="box"><small>COMPLETED</small><strong>{{ number_format($summary['completed']) }}</strong></div>
<div class="box"><small>CENTRE IRIS</small><strong>{{ number_format($summary['centre_iris']) }}</strong></div>
<div class="box"><small>ONLINE LAB</small><strong>{{ number_format($summary['online_lab']) }}</strong></div>
<div class="box"><small>CLASSROOM</small><strong>{{ number_format($summary['classroom']) }}</strong></div>
<div class="box"><small>AUTO MARK-OUT</small><strong>{{ number_format($summary['auto_checkout']) }}</strong></div>
<div class="box"><small>MINUTES</small><strong>{{ number_format($summary['minutes']) }}</strong></div>
</div>

<table>
<thead>
<tr>
<th>Date</th>
<th>Student</th>
<th>Course / Session</th>
<th>Mode</th>
<th>Source</th>
<th>Mark-In</th>
<th>Mark-Out</th>
<th>Exit Type</th>
<th>Minutes</th>
<th>Status</th>
</tr>
</thead>

<tbody>
@forelse($records as $record)
<tr>

<td>{{ optional($record->attendance_date)->format('d-m-Y') ?: '-' }}</td>

<td>
<strong>{{ $record->user?->name ?: '-' }}</strong><br>
{{ $record->user?->student_id ?: '-' }}
</td>

<td>
{{ $record->course?->code ?: '-' }}
@if($record->learningSession)
/ Session {{ $record->learningSession->session_number }}
<br>{{ $record->learningSession->title_en }}
@endif
</td>

<td>
@if($record->mode === 'online_lab')
Online Lab
@elseif($record->mode === 'classroom')
Classroom
@elseif($record->mode === 'lab' && $record->source === 'centre_iris')
Centre Iris Lab
@else
{{ ucfirst((string)$record->mode) }}
@endif
</td>

<td>
@if($record->source === 'centre_iris')
MIS100V2 Iris
@elseif($record->source === 'online_portal')
Online Portal
@elseif($record->recorded_by)
Manual Staff Entry
@else
System
@endif
</td>

<td>{{ optional($record->checked_in_at)->format('d-m-Y h:i A') ?: '-' }}</td>

<td>{{ optional($record->checked_out_at)->format('d-m-Y h:i A') ?: '-' }}</td>

<td>
@if($record->checkout_source === 'system_auto')
System Auto Mark-Out
@elseif($record->checkout_source === 'iris')
Iris Mark-Out
@elseif($record->checkout_source === 'courseware_completion')
Online Completion
@else
-
@endif
</td>

<td>{{ (int)$record->minutes_completed }}</td>

<td>{{ ucfirst((string)$record->status) }}</td>

</tr>
@empty
<tr>
<td colspan="10">No attendance records found for selected filters.</td>
</tr>
@endforelse
</tbody>
</table>

<div class="footer">
<div>Generated by KYP Attendance Management System</div>
<div>Authorized Attendance Report</div>
</div>

</body>
</html>
